[package]
name = "mailboxd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-lock = "3.4.1"
bragi = "0.2.0"

[dependencies.hel]
workspace = true

[dependencies.managarm]
workspace = true
